# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0e1062bbc6cdc41267c18fa62ddb37279622fe692350f895acb282d1048e26f6fb118fd86d5c712d41857f90446a4483968c9d4834ea82eaabf84e95d3db9fb2

test:
  secret_key_base: 8c0a49089abd28c408fc803e8fb01fbb2e106818d54a1b6a3f5597a7d0a4eb287ded206a2f5d3b4cb072abbb9ea9ac282718a216ff364054815fc6bf943218eb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
